// <auto-generated />
using System;
using FileUpload.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FileUpload.Migrations
{
    [DbContext(typeof(FileUploadContext))]
    partial class FileUploadContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FileUpload.Models.ConfigTransactionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CSVStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("XMLStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConfigTransactionStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CSVStatusName = "Approved",
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2022, 12, 18, 19, 12, 46, 330, DateTimeKind.Unspecified),
                            ShortName = "A",
                            XMLStatusName = "Approved"
                        },
                        new
                        {
                            Id = 2,
                            CSVStatusName = "Failed",
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2022, 12, 18, 19, 12, 46, 330, DateTimeKind.Unspecified),
                            ShortName = "R",
                            XMLStatusName = "Rejected"
                        },
                        new
                        {
                            Id = 3,
                            CSVStatusName = "Finished",
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2022, 12, 18, 19, 12, 46, 330, DateTimeKind.Unspecified),
                            ShortName = "D",
                            XMLStatusName = "Done"
                        });
                });

            modelBuilder.Entity("FileUpload.Models.ConfigUploadFileType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ConfigUploadFileType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2022, 12, 18, 19, 12, 46, 330, DateTimeKind.Unspecified),
                            Name = "CSV"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedDateTime = new DateTime(2022, 12, 18, 19, 12, 46, 330, DateTimeKind.Unspecified),
                            Name = "XML"
                        });
                });

            modelBuilder.Entity("FileUpload.Models.InvoiceTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("ConfigTransactionStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("ConfigUploadFileTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UploadedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UploadedGpSerialNo")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConfigTransactionStatusId");

                    b.HasIndex("ConfigUploadFileTypeId");

                    b.ToTable("InvoiceTransaction");
                });

            modelBuilder.Entity("FileUpload.Models.InvoiceTransaction", b =>
                {
                    b.HasOne("FileUpload.Models.ConfigTransactionStatus", "ConfigTransactionStatus")
                        .WithMany()
                        .HasForeignKey("ConfigTransactionStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FileUpload.Models.ConfigUploadFileType", "ConfigUploadFileType")
                        .WithMany()
                        .HasForeignKey("ConfigUploadFileTypeId");

                    b.Navigation("ConfigTransactionStatus");

                    b.Navigation("ConfigUploadFileType");
                });
#pragma warning restore 612, 618
        }
    }
}
